formatter: "markdown table"

recursive:
  enabled: true
  path: modules
  include-main: false

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: required

settings:
  anchor: true
  lockfile: false

sections:
  show:
    - requirements
    - providers
    - resources
    - inputs
    - outputs