name: TEST AWS Login
on:
  push:
    branches: [ "main" ]   
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.DEV_AWS_OIDC_IAM_ROLE_ARN }}
        aws-region: ${{ secrets.DEV_AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: CLI Login
      id: build-image
      run: |
        aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 773552202210.dkr.ecr.eu-west-1.amazonaws.com
        aws s3 ls




